spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
#      ddl-auto: create
      ddl-auto: update
#      ddl-auto: create-drop
    show_sql: true
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/student_service?allowPublicKeyRetrieval=true&useSSL=false
    password: root
    initialization-mode: never
#    initialization-mode: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error

