spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/student_service?allowPublicKeyRetrieval=true&useSSL=false
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
