openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://localhost:8080/

tags:
  - name: Pet
  - name: Course
  - name: Course Instance
  - name: User
  - name: Account
  - name: Enrollment
  - name: Test
  - name: LectureInstances

paths:
  /pets:
    $ref: 'api-paths/pet-api.yaml#/pets'
  /pets/{petId}:
    $ref: 'api-paths/pet-api.yaml#/pet-by-id'
  /courses:
    $ref: 'api-paths/course-api.yaml#/courses'
  /course-instances:
    $ref: 'api-paths/course-instance-api.yaml#/course-instances'
  /auth/login:
    $ref: 'api-paths/user-api.yaml#/users'
  /auth/register:
    $ref: 'api-paths/user-api.yaml#/user-register'
  /account:
    $ref: 'api-paths/account-api.yaml#/account'
  /account/payments:
    $ref: 'api-paths/account-api.yaml#/payments'
  /enrollments/my:
    $ref: 'api-paths/enrollment-api.yaml#/student-enrollments'
  /tests:
    $ref: 'api-paths/test.yaml#/tests'
  /tests/new:
    $ref: 'api-paths/test.yaml#/create-test'
  /lecture-instances/my:
    $ref: 'api-paths/lecture-instances.yaml#/lecture-instances'
  /tests/test-instances:
    $ref: 'api-paths/test.yaml#/test-instances'