openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://localhost:8080/

tags:
  - name: Pet

paths:
  /pets:
    $ref: 'api-paths/pet-api.yaml#/pets'
  /pets/{petId}:
    $ref: 'api-paths/pet-api.yaml#/pet-by-id'